### PR TITLE
redpanda: add support for overriding default flags

### LINKED ISSUE #1134: 🔹 Don't set duplicate CLI flags if provided by the end user
As it stands, if a user passes in an extra CLI flag to forward to redpanda that's already specified, it will be (incorrectly) provided twice.

This is most relevant in the context of `--memory` and `--reserve-memory`. In ~some~ most cases the built in memory calculations are tedious to understand and difficult to control. Instead, we should let users specify these flags directly and rely on their values rather than trying to force them through the charts memory calculations.

### PR DESCRIPTION
**Pull request by chrisseto**
#### 0c6068618df4a1b4bdacb6191df9d2f0bcd1a50f gotohelm: support delete and unset

This commits add support for transpiling the golang builtin `delete` and
sprig's `unset` helper.

#### 75d5a7848465aebe5f563acab856b47e026dc422 gotohelm: add support for concat and append

This commit adds support for sprig's `concat` helper and additionally
makes the golang builtin `append` work in all cases. Prior to this
commit `append` was limited to appending a single element, it now
supports multiple elements and spreading.

#### 690129a25d0f6eea86630e49e706fd0439ffea3e redpanda: add support for overriding default flags

Prior to this commit, users could not _directly_ control the value of
`--smp`, `--memory`, or `--reserve-memory`. This commit adds support for
overriding the defaults by specifying said flag in
`.statefulset.additionalRedpandaCmdFlags`.

For example, if a user passes `--smp=123` in, the chart's value for smp
will be ignored.

Fixes #1134

### CODE REVIEW

**Comment by chrisseto** [comment]
Happy to split this up into multiple PRs if that's preferred!

File: pkg/gotohelm/testdata/src/example/main.go [hunk 1]
```diff
@@ -39,6 +39,10 @@ func main() {
 			out = map[string]any{}
 		}
 
+		if err != nil {
+			err = fmt.Sprintf("%+v", err)
```
Comment (RafalKorepta) [inline pkg/gotohelm/testdata/src/example/main.go:43]: Why `fmt.Sprintf`?

File: pkg/gotohelm/transpiler_test.go [hunk 2]
```diff
@@ -254,11 +254,10 @@ func (g *GoRunner) Render(ctx context.Context, dot *helmette.Dot) (map[string]an
...
 	select {
 	case res := <-g.outputCh:
-		var err error
-		if e, ok := res["err"]; ok && e != nil {
-			return nil, fmt.Errorf("%#v", e)
+		if err, ok := res["err"]; ok && err != nil {
+			return nil, fmt.Errorf("error from go code: %s", err)
 		}
-		return res["result"].(map[string]any), err
+		return res["result"].(map[string]any), nil
```
Comment (RafalKorepta) [inline pkg/gotohelm/transpiler_test.go:260]: Good catch!

File: pkg/gotohelm/testdata/src/example/sprig/sprig.go [hunk 3]
```diff
@@ -15,9 +15,26 @@ func Sprig() map[string]any {
...
 	}
 }
 
+func unset() []map[string]int {
+	m1 := map[string]int{"0": 0, "1": 1, "2": 2}
+	m2 := map[string]int{"0": 0, "1": 1, "2": 2}
+	m3 := map[string]int{"0": 0, "1": 1, "2": 2}
+	m4 := map[string]int{"0": 0, "1": 1, "2": 2}
+
+	delete(m2, "0")
```
Comment (RafalKorepta) [inline pkg/gotohelm/testdata/src/example/sprig/sprig.go:37]: I'm not sure how `delete` transpilation maps to `unset` helm template.

File: pkg/gotohelm/helmette/sprig.go [hunk 4]
```diff
@@ -167,3 +167,8 @@ func MustFromJSON(data string) any {
 func Unset[K comparable, V any](d map[K]V, key K) {
 	delete(d, key)
 }
+
+// Concat is the go equivalent of sprig's `concat`.
+func Concat[T any](l1, l2 []T) []T {
```
Comment (RafalKorepta) [inline pkg/gotohelm/helmette/sprig.go:172]: Should it be 
```go
func Concat[T any](l1, l2 ...T) []T {
...
}
```

File: pkg/gotohelm/transpiler.go [hunk 5]
```diff
@@ -597,6 +599,7 @@ func (t *Transpiler) transpileCallExpr(n *ast.CallExpr) Node {
 		"helmette.MustFromJSON": "mustFromJson",
 		"helmette.MustToJSON":   "mustToJson",
 		"helmette.RegexMatch":   "regexMatch",
+		"helmette.SortAlpha":    "sortAlpha",
```
Comment (RafalKorepta) [inline pkg/gotohelm/transpiler.go:602]: Why `sortAlpha` is added to this commit?

File: charts/redpanda/configmap.tpl.go [hunk 6]
```diff
@@ -0,0 +1,64 @@
...
+import (
+	"fmt"
+
+	"github.com/redpanda-data/helm-charts/pkg/gotohelm/helmette"
+)
+
+// RedpandaAdditionalStartFlags returns a string list of flags suitable for use
+// as `additional_start_flags`. User provided flags will override any of those
+// set by default.
+func RedpandaAdditionalStartFlags(dot *helmette.Dot, smp, memory, reserveMemory string) []string {
```
Comment (RafalKorepta) [inline charts/redpanda/configmap.tpl.go:28]: Can you create go test for `RedpandaAdditionalStartFlags`?

File: charts/redpanda/configmap.tpl.go [hunk 7]
```diff
@@ -0,0 +1,64 @@
...
+	for flag := range chartFlags {
+		for _, userFlag := range values.Statefulset.AdditionalRedpandaCmdFlags {
+			if helmette.RegexMatch(fmt.Sprintf("^--%s", flag), userFlag) {
+				delete(chartFlags, flag)
+			}
+		}
+	}
+
+	// Deterministically order out list and add in values supplied flags.
+	keys := helmette.Keys(chartFlags)
```
Comment (RafalKorepta) [inline charts/redpanda/configmap.tpl.go:55]: `Keys` is not implemented 

https://github.com/redpanda-data/helm-charts/blob/b728456fe2d490a84100bb5e6fb2937deed4aa15/pkg/gotohelm/helmette/sprig.go#L36-L39

File: charts/redpanda/configmap.tpl.go (hunk 6 above)
Comment (RafalKorepta) [reply charts/redpanda/configmap.tpl.go:28]: NIT: Can smp, memory and reserveMemory be of type int or float?

File: charts/redpanda/testdata/30-additional-flags-override-values.yaml.golden [hunk 8]
```diff
@@ -0,0 +1,1402 @@
+---
```
Comment (RafalKorepta) [inline charts/redpanda/testdata/30-additional-flags-override-values.yaml.golden:1]: This file is too old. Please remote `charts/redpanda/Chart.lock` and re-run.

Comment (RafalKorepta) [reply charts/redpanda/testdata/30-additional-flags-override-values.yaml.golden:1]: https://github.com/redpanda-data/helm-charts/actions/runs/8559264006/job/23455747231?pr=1151#step:5:293

File: charts/redpanda/configmap.tpl.go [hunk 9]
```diff
@@ -0,0 +1,64 @@
...
+// set by default.
+func RedpandaAdditionalStartFlags(dot *helmette.Dot, smp, memory, reserveMemory string) []string {
+	values := helmette.Unwrap[Values](dot.Values)
+
+	// All `additional_start_flags` that are set by the chart.
+	chartFlags := map[string]string{
+		"smp":               smp,
+		"memory":            fmt.Sprintf("%sM", memory),
+		"reserve-memory":    fmt.Sprintf("%sM", reserveMemory),
+		"default-log-level": values.Logging.LogLevel,
```
[the remark this answers is not in the document]
Comment (chrisseto) [reply charts/redpanda/configmap.tpl.go:36]: The `logLevel` key is required by our JSON schema so there's no need to add a default here ;)

```
	LogLevel    string `json:"logLevel" jsonschema:"required,pattern=^(error|warn|info|debug|trace)$"`
```

Though the `logging` stanza isn't required... Might as well mark it as such given that we provide a default?

[the remark this answers is not in the document]
Comment (RafalKorepta) [reply charts/redpanda/configmap.tpl.go:36]: The values.yaml is not generated, so we need to make sure it is defined.

I'm fine leaving it as is.

File: charts/redpanda/templates/_configmap.go.tpl [hunk 10]
```diff
@@ -0,0 +1,31 @@
+{{- /* Generated from "configmap.tpl.go" */ -}}
+
+{{- define "redpanda.RedpandaAdditionalStartFlags" -}}
```
Comment (alejandroEsc) [inline charts/redpanda/templates/_configmap.go.tpl:3]: Just realized what bothers me about these files. Are we not supposed to indent?

**Review by alejandroEsc — COMMENTED** [review]
Just one question, still trying to get a hang of this.

File: pkg/gotohelm/testdata/src/example/sprig/sprig.go (hunk 3 above)
Comment (chrisseto) [reply pkg/gotohelm/testdata/src/example/sprig/sprig.go:37]: Golang's `delete` and sprig's `unset` are equivalent functions, no? They both remove a key from a dictionary/map.

File: charts/redpanda/templates/_configmap.go.tpl (hunk 10 above)
Comment (chrisseto) [reply charts/redpanda/templates/_configmap.go.tpl:3]: They're generated files, I didn't really intend for them to be human readable. Because everything is just JSON, there's no significance to the white space.

You're welcome to implement pretty printing, it might be a bit trickier than you think though.

File: charts/redpanda/configmap.tpl.go (hunk 9 above)
[the remark this answers is not in the document]
Comment (chrisseto) [reply charts/redpanda/configmap.tpl.go:36]: > The values.yaml is not generated, so we need to make sure it is defined.

If the field was omitted in the values.yaml but required in the JSON schema, all our tests would start failing. It's not generated yet but there is an enforced structure :D

File: pkg/gotohelm/testdata/src/example/sprig/sprig.go (hunk 3 above)
Comment (RafalKorepta) [reply pkg/gotohelm/testdata/src/example/sprig/sprig.go:37]: THX for explaining.

File: charts/redpanda/ci/30-additional-flags-override-novalues.yaml [hunk 11]
```diff
@@ -0,0 +1,4 @@
+statefulset:
```
Comment (RafalKorepta) [inline charts/redpanda/ci/30-additional-flags-override-novalues.yaml:1]: Could you add https://github.com/redpanda-data/helm-charts/blob/b14967ada018fc9be743665040a6191f187ed65a/.github/check-ci-files.sh#L14

`novalues.yaml` to the if statement? CI is failing at this moment with

```
verifying file: charts/redpanda/ci/30-additional-flags-override-novalues.yaml
- file does not match neither suffix '-values.yaml' nor -values.yaml.tpl'
```

https://github.com/redpanda-data/helm-charts/actions/runs/8602844060/job/23573322602?pr=1151#step:5:321

File: pkg/gotohelm/transpiler.go [hunk 12]
```diff
@@ -650,26 +651,27 @@ func (t *Transpiler) transpileCallExpr(n *ast.CallExpr) Node {
...
+		"helmette.ToJSON":       "toJson",
+		"helmette.Tpl":          "tpl",
+		"helmette.Trunc":        "trunc",
+		"helmette.Unset":        "unset",
 		"helmette.Upper":          "upper",
-		"maps.Keys":               "keys",
-		"math.Floor":              "floor",
+		"maps.Keys":             "keys",
+		"math.Floor":            "floor",
```
Comment (RafalKorepta) [inline pkg/gotohelm/transpiler.go]: NIT: go fmt was not executed against this file.

**Review by RafalKorepta — APPROVED** [review]
LGTM

CI just not pass ATM

File: charts/redpanda/testdata/99-none-existent-config-options-with-empty-values.yaml.golden [hunk 13]
```diff
@@ -623,7 +622,7 @@ kind: Deployment
 metadata:
   name: redpanda-console
   labels:
-    helm.sh/chart: console-0.7.25
+    helm.sh/chart: console-0.7.24
```
[the remark this answers is not in the document]
Comment (chrisseto) [reply charts/redpanda/testdata/99-none-existent-config-options-with-empty-values.yaml.golden:625]: Dang thought I fixed that. I guess the dep update command isn't doing what I was hoping for? I'll see if I can fix that.

[the remark this answers is not in the document]
Comment (chrisseto) [reply charts/redpanda/testdata/99-none-existent-config-options-with-empty-values.yaml.golden]: Fixed for this PR, going to make a tracking issue for dealing with this. I think I'm leaning towards checking in Chart.lock but excluding it from our releases.

[the remark this answers is not in the document]
Comment (chrisseto) [reply charts/redpanda/testdata/99-none-existent-config-options-with-empty-values.yaml.golden]: https://github.com/redpanda-data/helm-charts/issues/1166

File: pkg/gotohelm/testdata/src/example/main.go (hunk 1 above)
Comment (chrisseto) [reply pkg/gotohelm/testdata/src/example/main.go:44]: The JSON serialization of error sometimes is pretty worthless. Printf turns it into a human readable string that we can then show in the tests. I had a out of bounds error happening for a bit but the JSON version of it didn't contain any usable information it was just {}. The sprintf version had the full stacktrace
