### PR TITLE
redpanda: bump envsubst memory limits

### LINKED ISSUE #1564: Deploying a fresh cluster via helm chart is stuck at `bootstrap-yaml-envsubst` init container
### What happened?

Title

### What did you expect to happen?

Works

### How can we reproduce it (as minimally and precisely as possible)?. Please include values file.

<details>

```console
$ helm get values <redpanda-release-name> -n <redpanda-release-namespace> --all
affinity: {}
auditLogging:
  clientMaxBufferSize: 16777216
  enabled: false
  enabledEventTypes: null
  excludedPrincipals: null
  excludedTopics: null
  listener: internal
  partitions: 12
  queueDrainIntervalMs: 500
  queueMaxBufferSizePerShard: 1048576
  replicationFactor: null
auth:
  sasl:
    bootstrapUser:
      mechanism: SCRAM-SHA-256
    enabled: true
    mechanism: SCRAM-SHA-512
    secretRef: sasl-b5af2352
    users: []
clusterDomain: cluster.local
commonLabels: {}
config:
  cluster: {}
  node:
    crash_loop_limit: 5
  pandaproxy_client: {}
  rpk: {}
  schema_registry_client: {}
  tunable:
    compacted_log_segment_size: 67108864
    kafka_connection_rate_limit: 1000
    log_segment_size_max: 268435456
    log_segment_size_min: 16777216
    max_compacted_log_segment_size: 536870912
connectors:
  deployment:
    create: false
  enabled: false
  test:
    create: false
console:
  affinity: {}
  annotations: {}
  automountServiceAccountToken: true
  autoscaling:
    enabled: false
    maxReplicas: 100
    minReplicas: 1
    targetCPUUtilizationPercentage: 80
  commonLabels: {}
  config: {}
  configmap:
    create: false
  console:
    config: {}
  deployment:
    create: false
  enabled: true
  enterprise:
    licenseSecretRef:
      key: ""
      name: ""
  extraContainers: []
  extraEnv: []
  extraEnvFrom: []
  extraVolumeMounts: []
  extraVolumes: []
  fullnameOverride: ""
  global: {}
  image:
    pullPolicy: IfNotPresent
    registry: docker.redpanda.com
    repository: redpandadata/console
    tag: ""
  imagePullSecrets: []
  ingress:
    annotations: {}
    className: null
    enabled: false
    hosts:
    - host: chart-example.local
      paths:
      - path: /
        pathType: ImplementationSpecific
    tls: []
  initContainers:
    extraInitContainers: ""
  livenessProbe:
    failureThreshold: 3
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  nameOverride: ""
  nodeSelector: {}
  podAnnotations: {}
  podLabels: {}
  podSecurityContext:
    fsGroup: 99
    runAsUser: 99
  priorityClassName: ""
  readinessProbe:
    failureThreshold: 3
    initialDelaySeconds: 10
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  replicaCount: 1
  resources: {}
  secret:
    create: false
    enterprise: {}
    kafka: {}
    login:
      github: {}
      google: {}
      jwtSecret: ""
      oidc: {}
      okta: {}
    redpanda:
      adminApi: {}
  secretMounts: []
  securityContext:
    runAsNonRoot: true
  service:
    annotations: {}
    port: 8080
    targetPort: null
    type: ClusterIP
  serviceAccount:
    annotations: {}
    automountServiceAccountToken: true
    create: true
    name: ""
  strategy: {}
  tests:
    enabled: true
  tolerations: []
  topologySpreadConstraints: []
enterprise:
  license: ""
  licenseSecretRef: {}
external:
  addresses:
  - localhost
  enabled: true
  service:
    enabled: true
  type: NodePort
fullnameOverride: ""
image:
  pullPolicy: IfNotPresent
  repository: docker.redpanda.com/redpandadata/redpanda
  tag: ""
imagePullSecrets: []
license_key: ""
license_secret_ref: {}
listeners:
  admin:
    external:
      default:
        advertisedPorts:
        - 31644
        enabled: false
        port: 9645
        tls:
          cert: external
    port: 9644
    tls:
      cert: default
      requireClientAuth: false
  http:
    authenticationMethod: null
    enabled: true
    external:
      default:
        advertisedPorts:
        - 30912
        authenticationMethod: null
        port: 8083
        tls:
          cert: external
          requireClientAuth: false
    kafkaEndpoint: default
    port: 8082
    tls:
      cert: default
      requireClientAuth: false
  kafka:
    authenticationMethod: null
    external:
      default:
        advertisedPorts:
        - 30910
        authenticationMethod: null
        port: 9094
        tls:
          cert: external
    port: 9093
    tls:
      cert: default
      requireClientAuth: false
  rpc:
    port: 33145
    tls:
      cert: default
      requireClientAuth: false
  schemaRegistry:
    authenticationMethod: null
    enabled: false
    external:
      default:
        advertisedPorts:
        - 30081
        authenticationMethod: null
        port: 8084
        tls:
          cert: external
          requireClientAuth: false
    kafkaEndpoint: default
    port: 8081
    tls:
      cert: default
      requireClientAuth: false
logging:
  logLevel: info
  usageStats:
    enabled: true
monitoring:
  enabled: false
  labels: {}
  scrapeInterval: 30s
nameOverride: ""
nodeSelector: {}
post_install_job:
  affinity: {}
  enabled: true
  podTemplate:
    annotations: {}
    labels: {}
    spec:
      containers:
      - env: []
        name: post-install
        securityContext: {}
      securityContext: {}
rackAwareness:
  enabled: false
  nodeAnnotation: topology.kubernetes.io/zone
rbac:
  annotations: {}
  enabled: false
resources:
  cpu:
    cores: 1
  memory:
    container:
      max: 2.5Gi
serviceAccount:
  annotations: {}
  create: false
  name: ""
statefulset:
  additionalRedpandaCmdFlags: []
  additionalSelectorLabels: {}
  annotations: {}
  budget:
    maxUnavailable: 1
  extraVolumeMounts: ""
  extraVolumes: ""
  initContainerImage:
    repository: busybox
    tag: latest
  initContainers:
    configurator:
      extraVolumeMounts: ""
      resources: {}
    extraInitContainers: ""
    fsValidator:
      enabled: false
      expectedFS: xfs
      extraVolumeMounts: ""
      resources: {}
    setDataDirOwnership:
      enabled: false
      extraVolumeMounts: ""
      resources: {}
    setTieredStorageCacheDirOwnership:
      extraVolumeMounts: ""
      resources: {}
    tuning:
      extraVolumeMounts: ""
      resources: {}
  livenessProbe:
    failureThreshold: 3
    initialDelaySeconds: 10
    periodSeconds: 10
  nodeSelector: {}
  podAffinity: {}
  podAntiAffinity:
    custom: {}
    topologyKey: kubernetes.io/hostname
    type: hard
    weight: 100
  podTemplate:
    annotations: {}
    labels: {}
    spec:
      containers:
      - env: []
        name: redpanda
        securityContext: {}
      securityContext: {}
  priorityClassName: ""
  readinessProbe:
    failureThreshold: 3
    initialDelaySeconds: 1
    periodSeconds: 10
    successThreshold: 1
  replicas: 1
  securityContext:
    fsGroup: 101
    fsGroupChangePolicy: OnRootMismatch
    runAsUser: 101
  sideCars:
    configWatcher:
      enabled: true
      extraVolumeMounts: ""
      resources: {}
      securityContext: {}
    controllers:
      createRBAC: true
      enabled: false
      healthProbeAddress: :8085
      image:
        repository: docker.redpanda.com/redpandadata/redpanda-operator
        tag: v2.2.4-24.2.5
      metricsAddress: :9082
      resources: {}
      run:
      - all
      securityContext: {}
  startupProbe:
    failureThreshold: 120
    initialDelaySeconds: 1
    periodSeconds: 10
  terminationGracePeriodSeconds: 90
  tolerations: []
  topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: topology.kubernetes.io/zone
    whenUnsatisfiable: ScheduleAnyway
  updateStrategy:
    type: RollingUpdate
storage:
  hostPath: /dev/kafka
  persistentVolume:
    annotations: {}
    enabled: false
    labels: {}
    nameOverwrite: ""
    size: 20Gi
    storageClass: ""
  tiered:
    config:
      cloud_storage_cache_size: 5368709120
      cloud_storage_enable_remote_read: true
      cloud_storage_enable_remote_write: true
      cloud_storage_enabled: false
    credentialsSecretRef:
      accessKey:
        configurationKey: cloud_storage_access_key
      secretKey:
        configurationKey: cloud_storage_secret_key
    hostPath: ""
    mountType: emptyDir
    persistentVolume:
      annotations: {}
      labels: {}
      storageClass: ""
tests:
  enabled: true
tls:
  certs:
    default:
      caEnabled: true
    external:
      caEnabled: true
  enabled: false
tolerations: []
tuning:
  tune_aio_events: true
```

</details>

### Anything else we need to know?

_No response_

### Which are the affected charts?

Redpanda

### Chart Version(s)

<details>

```console
$ helm -n <redpanda-release-namespace> list 
redpanda-ba4e1924  	test	1       	2024-10-15 13:58:45.893116 +1000 AEST	failed  	redpanda-5.9.7   	v24.2.7 
```

</details>

### Cloud provider

<details>
orbstack mac pro m2
</details>

JIRA Link: [K8S-388](https://redpandadata.atlassian.net/browse/K8S-388)

### PR DESCRIPTION
**Pull request by chrisseto**
Prior to this commit the memory limits of the `bootstrap-yaml-envsubst` container were set to 25Mi. This value was accidentally lower than the total size of the binary itself, 80Mi, which seemingly surfaced as unexplained hangs when _initially_ run on aarch64 (specifically using obstack).

This commit bumps the limit to 125Mi to ensure adequate headroom which seems to mitigate such hangs. The exact mechanisms at play here at not well known.

Fixes #1564

### CODE REVIEW

**Review by RafalKorepta — APPROVED** [review]
LGTM

File: charts/redpanda/post_install_upgrade_job.go [hunk 1]
```diff
@@ -55,11 +55,11 @@ func bootstrapYamlTemplater(dot *helmette.Dot) corev1.Container {
 		Resources: corev1.ResourceRequirements{
 			Limits: corev1.ResourceList{
 				corev1.ResourceCPU:    resource.MustParse("100m"),
-				corev1.ResourceMemory: resource.MustParse("25Mi"),
+				corev1.ResourceMemory: resource.MustParse("125Mi"),
```
Comment (andrewstucki) [inline charts/redpanda/post_install_upgrade_job.go:58]: We should probably make these configurable in the `values.yaml`

**Review by andrewstucki — APPROVED** [review]

File: charts/redpanda/post_install_upgrade_job.go (hunk 1 above)
Comment (chrisseto) [reply charts/redpanda/post_install_upgrade_job.go:58]: It was actually an active decision to make them not configurable. My logic here being "If it's correct, why would anyone need to set it to anything else?". Despite the extremely weird bug, I think I still agree with that logic. We can expand `podSpec` to allow overriding the resources of `initContainers` if you think that's safer/better? Though I'll do that at a later time rather than in this release unless you feel strongly.

Comment (chrisseto) [reply charts/redpanda/post_install_upgrade_job.go:58]: By `podSpec` I mean: https://github.com/redpanda-data/helm-charts/blob/6bf59059c8a90772d692c73baff5b700a5b939e2/charts/redpanda/helpers.go#L426

Comment (andrewstucki) [reply charts/redpanda/post_install_upgrade_job.go:58]: Yeah, I'm thinking it would be good to do it a later time, definitely don't need to handle it now.

My $0.02 is that in general I'm a fan of keeping at least some hardcoded things a bit more configurable if they're going to make installation otherwise impossible, especially if we make other things around the pod running configurable (i.e. the image). I can totally imagine someone repackaging a custom image that for some reason needs slightly different resource limits.

Comment (chrisseto) [reply charts/redpanda/post_install_upgrade_job.go:58]: That's fair! I'm generally onboard as well. I've just been reticent to fully implement SMP in gotohelm and I really want to avoid stabbing any more holes into our already very inconsistent API.

Comment (chrisseto) [reply charts/redpanda/post_install_upgrade_job.go:58]: https://github.com/redpanda-data/helm-charts/issues/1571
